name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'trying'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build Bevy Assets"
        run: cd generate-assets && ./generate_assets.sh

      - name: "Build Bevy Error Codes"
        run: cd generate-errors && ./generate_errors.sh

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: "Build Bevy Examples"
        run: cargo install wasm-bindgen-cli && cd generate-wasm-examples && ./generate_wasm_examples.sh

      - name: "Build website"
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_ONLY: true
          TOKEN: fake-secret

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run Markdown Lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: master
          # Not needed here as only one Linter is used.
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-code:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2

       - uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           components: rustfmt, clippy
           override: true

       - name: Install alsa and udev
         run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

       - name: Build & run tests
         run: cd code-validation && cargo test
